// app/layout.tsx
import { Inder , Gugi , Julee , Poppins} from "next/font/google";

import "./globals.css";
import ReduxProvider from "./Redux/provider";



// استخدام خط Inder كافتراضي
const inder = Inder({ subsets: ["latin"], weight: "400" });
const gugi = Gugi({ subsets: ["latin"], weight: "400" });
const julee = Julee({ subsets: ["latin"], weight: "400" });
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inder.className} ${gugi.className} ${julee.className} ${poppins.className} antialiased`}>
       <ReduxProvider>
        {children}
       </ReduxProvider>
   
      </body>
    </html>
  );
}
